### ISSUE TITLE
Magento 2.1.3 support

### ISSUE THREAD

**Issue by anebi** [karliuka/m2.ShippingTweaks#1]
Hi, 

I tested your code with Magento 2.1.3 and it works perfectly.

May I ask you to change composer requirements so we can install the addon thru composer on Magento 2.1.x too?

I installed it manually and tested like that, but having it available thru composer would be good too.

Thanks for your work and time for creating this. It is in big help.

Regards,
Ali Nebi

**Comment by anebi** [comment]
One issue that i just saw. It works ok on frontend, but in backend i get now error report message with following error:

`:4:{i:0;s:187:"Warning: Invalid argument supplied for foreach() in /var/www/vhosts/sm-final.asgard.iguanait.com/httpdocs/vendor/magento/module-config/Model/Config/Structure/Mapper/Sorting.php on line 34";i:1;s:7912:"#0
`
For some reason it brakes the admin. If module is disabled, then backend start working properly again without errors.

**Comment by karliuka** [comment]
fixed

**Comment by anebi** [comment]
Thanks :)

**Comment by anebi** [comment]
It looks like this new version is not working. I reverted to previous version. Backend issue is caused by tabs inside system.xml. Once you remove the tabs, then backend is working ok.

**Comment by karliuka** [comment]
Sorry, to commit the wrong version. Frontend now works.

**Comment by anebi** [comment]
Yes, frontend is ok now :)

You still have to remove all tabs from etc/adminhtml/system.xml too, because this causes backend to return fatal error :)

**Comment by karliuka** [comment]
It seems this file had problems with encoding. On earlier versions of the magento (testable 2.0.4) is very delicate xmlReader ) Check, please

**Comment by anebi** [comment]
It works ok now without any errors in frontend or backend. Thanks again! Great work and support :)
