### ISSUE TITLE
error : could not find package error in magento 2.2

### ISSUE THREAD

**Issue by rajeevjan1991** [karliuka/m2.ShippingTweaks#2]
hi i'm trying to install it but getting error PFA
![screenshot 157](https://user-images.githubusercontent.com/33253321/32591307-9804bfa6-c544-11e7-84b4-a730c6179849.png)

**Comment by karliuka** [comment]
Thanks you. This is fixed. Check, please.

**Comment by rajeevjan1991** [comment]
WOW its working now .
Thanks karliuka.

**Comment by rajeevjan1991** [comment]
have you developed extension for price slider in layered navigation and custom cash on delivery fee based on cart amount.
