### ISSUE TITLE
Dosent work with Table Rates

### ISSUE THREAD

**Issue by gfasidis** [karliuka/m2.ShippingTweaks#6]
Hello is it possible to fix compability with table rates?

**Comment by karliuka** [comment]
please, you can specify more detailed information ?

**Comment by gfasidis** [comment]
Magento Version: 2.3.3
m2.ShippingTweaks: 2.0.1

When i enable your module the table rate shipping method missing from checkout/cart and always show Free Shipping method. When i disable it all is back to normal

**Comment by karliuka** [comment]
thank,
The logic of m2.ShippingTweaks is that it hides shipping methods whose cost is more than zero (de fact, it leaves free shipping if it is active in the system and also methods whose cost is zero) . this is the general idea of the module. if the table rate module does not contain a value of zero for the current region (region must be selected), then everything works correctly (what do you see).
maybe you have another case ...

**Comment by gfasidis** [comment]
![module_disable](https://user-images.githubusercontent.com/28733848/68112614-61f16580-fefa-11e9-968a-8a470e226344.png)
![module_enable](https://user-images.githubusercontent.com/28733848/68112615-6289fc00-fefa-11e9-8c81-6c768b9a79cf.png)

First image module is disable.. show me both shipping methods
Second image module is enable and only show me free shipping error notice (You must buy 350€ and more to have free shipping). Total in cart is below 350€

**Comment by karliuka** [comment]
thank you, I will check this moment
