### ISSUE TITLE
Unable to install the plugin 2.4.0

### ISSUE THREAD

**Issue by ShyamSuchakATP** [karliuka/m2.ShippingTweaks#9]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for faonni/module-shipping-tweaks 2.4 -> satisfiable by faonni/module-shipping-tweaks[2.4.0].
    - Can only install one of: laminas/laminas-code[3.4.1, 3.3.2].
    - Can only install one of: laminas/laminas-code[3.4.1, 3.3.2].
    - Can only install one of: laminas/laminas-code[3.4.1, 3.3.2].
    - Conclusion: install laminas/laminas-code 3.4.1
    - Installation request for laminas/laminas-code (locked at 3.3.2) -> satisfiable by laminas/laminas-code[3.3.2].

Installation failed, reverting ./composer.json to its original content.

**Comment by karliuka** [comment]
Sorry, but the shipping tweaks module has no direct dependency on the laminas framework. Please try to just update your installation using the command before installing:
`composer update`
